sudo: required
services:
  - docker
before_install:
  - docker build -t datasciencedotuniversity/dockeer-react -f Dockerfile.dev .
script:
  - docker run datasciencedotuniversity/dockeer-react npm test -- --coverage